# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbelt2app', '0002_auto_20160823_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
